# Enable stateless CSRF protection for forms and logins/logouts
framework:
    secret: '%env(APP_SECRET)%'

    session:
        enabled: true

    csrf_protection:
        check_header: true
        stateless_token_ids:
            - submit
            - authenticate
            - logout
        enabled: true
